package io.celox.notifvault

import io.celox.notifvault.ui.about.AboutLinks
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * The README badges (version, unit tests, lines of code, test code) are generated by
 * scripts/update-badges.py. This test counts the same way and fails when a badge drifts — a
 * hand-typed number is wrong the day after it was typed. Run the script, never edit the badges.
 */
class ReadmeBadgesTest {

    private val root = File("..").takeIf { File(it, "README.md").exists() } ?: File(".")
    private val readmes = listOf(File(root, "README.md"), File(root, "README.de.md"))

    private fun kt(sub: String) = File(root, sub).walkTopDown().filter { it.isFile && it.extension == "kt" }

    private fun nonBlank(sub: String) = kt(sub).sumOf { f -> f.readLines().count { it.isNotBlank() } }

    private fun tests() = kt("app/src/test").sumOf { f ->
        Regex("""^\s*@Test\b""", RegexOption.MULTILINE).findAll(f.readText()).count()
    }

    /** Same rounding as update-badges.py: 9876 → "9.9k", 950 → "950". */
    private fun k(n: Int): String = if (n < 1000) "$n" else String.format(java.util.Locale.ROOT, "%.1fk", n / 1000.0)

    private fun badge(text: String, label: String): String? =
        Regex("""img\.shields\.io/badge/${Regex.escape(label)}-([^-?"]+)-""").find(text)?.groupValues?.get(1)

    @Test
    fun `badges show the current numbers - run scripts update-badges py`() {
        val expected = mapOf(
            "version" to BuildConfig.VERSION_NAME,
            "unit%20tests" to "${tests()}",
            "lines%20of%20code" to k(nonBlank("app/src/main")),
            "test%20code" to k(nonBlank("app/src/test")),
        )
        for (readme in readmes) {
            val text = readme.readText()
            for ((label, value) in expected) {
                assertEquals("${readme.name}: badge '$label'", value, badge(text, label))
            }
        }
    }

    @Test
    fun `the product page's stats file matches as well`() {
        val json = File(root, ".github/repo-stats.json").readText()
        fun num(key: String) = Regex("\"$key\"\\s*:\\s*(\\d+)").find(json)!!.groupValues[1].toInt()
        assertEquals(nonBlank("app/src/main"), num("loc_main"))
        assertEquals(nonBlank("app/src/test"), num("loc_test"))
        assertEquals(tests(), num("tests"))
    }

    @Test
    fun `both READMEs carry the same badges and link each other`() {
        val (en, de) = readmes.map { it.readText() }
        val badges = { t: String -> Regex("""img\.shields\.io/[^"\s)]+""").findAll(t).map { it.value }.toSet() }
        assertEquals(badges(en), badges(de))
        assertTrue(en.contains("(README.de.md)"))
        assertTrue(de.contains("(README.md)"))
    }

    @Test
    fun `the donate link is the one the app uses`() {
        val donate = AboutLinks.donateUrl()
        readmes.forEach { assertTrue("${it.name} lacks the app's PayPal link", it.readText().contains(donate)) }
    }

    @Test
    fun `every local image the READMEs show exists`() {
        for (readme in readmes) {
            val paths = Regex("""src="((?!https?:)[^"]+)"""").findAll(readme.readText()).map { it.groupValues[1] }.toList()
            assertTrue("${readme.name} shows no local images", paths.isNotEmpty())
            paths.forEach { assertTrue("${readme.name}: missing $it", File(root, it).exists()) }
        }
    }

    @Test
    fun `each README shows the screenshots in its own language`() {
        assertTrue(File(root, "README.md").readText().contains("docs/screenshots/en-overview.webp"))
        assertTrue(File(root, "README.de.md").readText().contains("docs/screenshots/de-overview.webp"))
    }
}
