package io.celox.notifvault.ui.theme

import androidx.compose.ui.graphics.Color

// Brand: the teal of the parrot's safe, amber of the padlock, the ink night sky behind them
// (the dark surface is the hero artwork's background, #0D1528).
val Teal = Color(0xFF14B8A6)
val TealDark = Color(0xFF0D9488)
val Ink = Color(0xFF0D1528)
val Slate = Color(0xFF334155)
val Mist = Color(0xFFF1F5F9)
val Amber = Color(0xFFF59E0B)

// ---- Dark scheme ----
val DarkPrimary = Color(0xFF5EEAD4)
val DarkOnPrimary = Color(0xFF003731)
val DarkPrimaryContainer = Color(0xFF0F766E)
val DarkOnPrimaryContainer = Color(0xFFCCFBF1)
val DarkSecondary = Color(0xFFB2CCC7)
val DarkOnSecondary = Color(0xFF1D3531)
val DarkSecondaryContainer = Color(0xFF344B47)
val DarkOnSecondaryContainer = Color(0xFFCDE8E2)
val DarkTertiary = Color(0xFFFCD34D)
val DarkOnTertiary = Color(0xFF3F2E00)
val DarkTertiaryContainer = Color(0xFF5C4300)
val DarkOnTertiaryContainer = Color(0xFFFFE08F)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkSurface = Ink
val DarkOnSurface = Color(0xFFE2E8F0)
val DarkSurfaceVariant = Color(0xFF334155)
val DarkOnSurfaceVariant = Color(0xFFC3CCD8)
val DarkSurfaceContainerLowest = Color(0xFF080E1C)
val DarkSurfaceContainerLow = Color(0xFF121B30)
val DarkSurfaceContainer = Color(0xFF162137)
val DarkSurfaceContainerHigh = Color(0xFF1D2941)
val DarkSurfaceContainerHighest = Color(0xFF26334C)
val DarkOutline = Color(0xFF8491A4)
val DarkOutlineVariant = Color(0xFF3A475C)
val DarkInverseSurface = Color(0xFFE2E8F0)
val DarkInverseOnSurface = Color(0xFF1E293B)

// ---- Light scheme ----
val LightPrimary = Color(0xFF0F766E)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFBDF4EA)
val LightOnPrimaryContainer = Color(0xFF00201C)
val LightSecondary = Color(0xFF4A6360)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCCE8E3)
val LightOnSecondaryContainer = Color(0xFF051F1C)
val LightTertiary = Color(0xFF8A5300)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFDDB3)
val LightOnTertiaryContainer = Color(0xFF2B1700)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightSurface = Color(0xFFF8FAFC)
val LightOnSurface = Color(0xFF0F172A)
val LightSurfaceVariant = Color(0xFFE2E8F0)
val LightOnSurfaceVariant = Color(0xFF475569)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF1F5F9)
val LightSurfaceContainer = Color(0xFFEBF0F5)
val LightSurfaceContainerHigh = Color(0xFFE5EBF1)
val LightSurfaceContainerHighest = Color(0xFFDEE5EC)
val LightOutline = Color(0xFF64748B)
val LightOutlineVariant = Color(0xFFCBD5E1)
val LightInverseSurface = Color(0xFF1E293B)
val LightInverseOnSurface = Color(0xFFF1F5F9)
