// WebMCP tools: lets an AI agent in the browser ask this page for facts and actions directly instead of
// scraping it (https://developer.chrome.com/docs/ai/webmcp). Only registered where the browser offers
// `modelContext`; everywhere else this file does nothing. All data comes from the same places the page
// uses — latest.json and changelog.md on this origin — so tools and page can never disagree.
(function () {
  'use strict';

  var mc = (typeof document !== 'undefined' && document.modelContext) ||
    (typeof navigator !== 'undefined' && navigator.modelContext);
  if (!mc || typeof mc.registerTool !== 'function') return;

  // Facts from site.json (generated by build.py).
  var FACTS = {
    "name": "Kleene Petze",
    "summary": "Kleene Petze is a free, open-source (MIT) Android app for Android 8.0 and later that saves incoming message notifications permanently and encrypted on the device — like Android's notification history, but without the 24-hour expiry. Because WhatsApp posts no notification when a message is deleted, the copy captured on arrival survives: messages the sender deletes while they are still unread stay readable and are marked as deleted, and earlier versions of edited messages are kept too. It works for WhatsApp, WhatsApp Business, Signal, Telegram, Instagram, Messenger and Google Messages, or for every app. Messages are grouped into chats, searchable, and can be exported and imported as an encrypted file, JSON or CSV. The database is encrypted with SQLCipher (AES-256), an optional biometric lock protects the app, and nothing leaves the phone; the only network access is an update check that is off unless you switch it on. Distributed as a signed APK through GitHub Releases.",
    "requirements": {
      "android": "Android 8.0+"
    },
    "platforms": [
      "WhatsApp",
      "WhatsApp Business",
      "Signal",
      "Telegram",
      "Instagram",
      "Messenger",
      "Google Messages"
    ],
    "features": [
      "Permanent archive of incoming message notifications, grouped into chats",
      "Messages deleted by the sender while unread stay readable and are marked as deleted",
      "Earlier versions of edited messages are kept and marked",
      "“Uncovered” view listing every deleted and edited message across all chats",
      "Works with WhatsApp, WhatsApp Business, Signal, Telegram, Instagram, Messenger, Google Messages — or every app",
      "Pictures: the preview image a notification carries is saved too (optional)",
      "Full-text search with highlighted matches",
      "Encrypted database (SQLCipher, AES-256) with the key in the Android Keystore",
      "Optional biometric or screen-lock app lock; hidden from the recent-apps preview while it is on",
      "Export and import of the whole archive as an encrypted file, JSON or CSV — import only adds, never overwrites",
      "Export of a single chat as CSV or JSON",
      "Optional retention period for automatic deletion of old messages",
      "Self-healing capture: reconnects after reboots and app updates, with a status check in Settings",
      "Material 3 Expressive interface with light, dark and system theme",
      "Opt-in update check: a daily look at the newest version, a notification when one is out",
      "No ads, no tracking, no account; nothing leaves the device",
      "English and German, including per-app language on Android 13+"
    ],
    "limits": [
      "Android only; not on Google Play — distributed as an APK through GitHub Releases.",
      "Only messages that arrive as a notification on this phone are saved: muted chats and messages you receive while the chat is open often post none.",
      "A message deleted after you have already read it cannot be recovered — there is no notification left to keep.",
      "Voice messages, videos and original files are never part of a notification; pictures are kept only as the smaller preview.",
      "The interface is available in English and German only.",
      "It does not download or install updates by itself — it only tells you, and you install the new APK over the old one."
    ],
    "targets": [
      "android"
    ],
    "signing": [
      {
        "what": "Signing certificate SHA-256",
        "value": "0560befbf32c64ede5a518a18bf6799c44f85b45853e97723914d4a84aafe379"
      }
    ],
    "links": {
      "page": "https://kleene-petze.celox.io/",
      "download": "https://kleene-petze.celox.io/download",
      "latest": "https://kleene-petze.celox.io/latest.json",
      "markdown": "https://kleene-petze.celox.io/index.md",
      "changelog": "https://kleene-petze.celox.io/changelog.md",
      "skill": "https://kleene-petze.celox.io/skills/get-kleene-petze/SKILL.md",
      "source": "https://github.com/pepperonas/kleene-petze",
      "licence": "https://github.com/pepperonas/kleene-petze/blob/main/LICENSE"
    }
  };
  var SITE = FACTS.links.page.replace(/\/$/, '');
  var LANGS = ["en", "de", "es", "it", "fr"];

  function latest(signal) {
    return fetch('/latest.json', { cache: 'no-cache', signal: signal }).then(function (r) {
      if (!r.ok) throw new Error('latest.json: HTTP ' + r.status);
      return r.json();
    });
  }
  function json(v) { return JSON.stringify(v, null, 2); }
  var READ = { readOnlyHint: true };

  var tools = [
    {
      name: 'get_app_facts',
      description: 'What Kleene Petze is: a one-paragraph summary, requirements, supported platforms, ' +
        'features, limits and the important links (download, source, changelog, licence).',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
      annotations: READ,
      execute: function () { return Promise.resolve(json(FACTS)); }
    },
    {
      name: 'get_latest_release',
      description: 'The newest release of Kleene Petze: version, publication date, release notes URL ' +
        'and every file with its download URL, size in bytes and SHA-256.',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
      annotations: READ,
      execute: function (_input, opts) {
        return latest(opts && opts.signal).then(function (d) {
          return json({ version: d.version, published: d.published, notes: d.notes, assets: d.assets ||
            [{ target: FACTS.targets[0], name: d.name, url: d.url, size: d.size, sha256: d.sha256 }] });
        });
      }
    },
    {
      name: 'get_download_url',
      description: 'The direct download URL of the newest Kleene Petze file for a platform (android), plus ' +
        'the stable link that always redirects to the newest file.',
      inputSchema: {
        type: 'object',
        properties: { platform: { type: 'string', enum: FACTS.targets, description: 'Target platform; default: ' + FACTS.targets[0] + '.' } },
        additionalProperties: false
      },
      annotations: READ,
      execute: function (input, opts) {
        return latest(opts && opts.signal).then(function (d) {
          var assets = d.assets || [{ target: FACTS.targets[0], name: d.name, url: d.url, size: d.size }];
          var want = (input && input.platform) || assets[0].target;
          var a = assets.filter(function (x) { return x.target === want; })[0] || assets[0];
          return json({ version: d.version, platform: a.target, file: a.name, url: a.url, size: a.size,
            stable_link: SITE + '/download/' + a.target });
        });
      }
    },
    {
      name: 'get_checksums',
      description: 'How to verify a downloaded Kleene Petze file: the SHA-256 of every file of the newest release ' +
        'and the fixed signing facts.',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
      annotations: READ,
      execute: function (_input, opts) {
        return latest(opts && opts.signal).then(function (d) {
          var assets = d.assets || [{ name: d.name, sha256: d.sha256 }];
          return json({ version: d.version,
            files: assets.map(function (a) { return { name: a.name, sha256: a.sha256 }; }),
            signing: FACTS.signing });
        });
      }
    },
    {
      name: 'get_changelog',
      description: 'The most recent entries of the Kleene Petze changelog as Markdown.',
      inputSchema: {
        type: 'object',
        properties: { versions: { type: 'integer', minimum: 1, maximum: 10, description: 'How many versions (default 3).' } },
        additionalProperties: false
      },
      annotations: READ,
      execute: function (input, opts) {
        var n = Math.min(10, Math.max(1, (input && input.versions) || 3));
        return fetch('/changelog.md', { cache: 'no-cache', signal: opts && opts.signal }).then(function (r) {
          if (!r.ok) throw new Error('changelog.md: HTTP ' + r.status);
          return r.text();
        }).then(function (md) {
          var parts = md.split(/\n(?=## \[)/).slice(1).filter(function (s) { return !/^## \[Unreleased\]\s*$/.test(s.trim()); });
          return parts.slice(0, n).join('\n').trim();
        });
      }
    },
    {
      name: 'set_page_language',
      description: 'Show this page in another language (English, German, Spanish, Italian or French).',
      inputSchema: {
        type: 'object',
        properties: { language: { type: 'string', enum: LANGS, description: 'ISO 639-1 code.' } },
        required: ['language'],
        additionalProperties: false
      },
      annotations: { readOnlyHint: false },
      execute: function (input) {
        if (LANGS.indexOf(input.language) < 0) throw new Error('unsupported language: ' + input.language);
        if (typeof window.SITE_setLanguage === 'function') window.SITE_setLanguage(input.language);
        return Promise.resolve('Page language set to ' + input.language + '.');
      }
    }
  ];

  tools.forEach(function (t) {
    try { mc.registerTool(t); } catch (e) { /* a browser with an older WebMCP shape: skip that tool */ }
  });
})();
